# Deep Learning Project

By Rachel Bankier, Marie Berchichasvili and Nafi Anna Dramé

This project works with the implicit hate dataset : [github : SALT-NLP implicit-hate](https://github.com/SALT-NLP/implicit-hate?tab=readme-ov-file) from SALT-NIP. 
We aim at training a model that distinguish implicit from explicit hate speech

## 1. Load Dataset and inport

In [6]:
import torch
import torch.nn as nn
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np

What file do we have in our dataset : 

implicit_hate_v1_SAP_posts.tsv : Raw data with hateful post, come are hateful other aren't
stg1 : 3 category classification : Implicit hate, not hate and explicit_hate
stg3 : Target and implied statement

In [7]:
# Load the tsv data in data/implicit-hate-corpus

DATA_FOLDER = "data/implicit-hate-corpus"
raw_dataset = pd.read_csv(f"{DATA_FOLDER}/implicit_hate_v1_SAP_posts.tsv", sep="\t")
stg1 = pd.read_csv(f"{DATA_FOLDER}/implicit_hate_v1_stg1_posts.tsv", sep="\t")
stg2 = pd.read_csv(f"{DATA_FOLDER}/implicit_hate_v1_stg2_posts.tsv", sep="\t")
stg3 = pd.read_csv(f"{DATA_FOLDER}/implicit_hate_v1_stg3_posts.tsv", sep="\t")

In [8]:
# Quick inspection of the data
raw_dataset.head()

          ID                                               post
0  SAP_10011  Guys I have a question: when a gay couple gets...
1  SAP_10036  Heard this from a 12 year old: 'Whats the diff...
2  SAP_10045  Friend: how dark is your humor? Me: If you whi...
3  SAP_10051  What do you say to a black guy in a three piec...
4  SAP_10085  how do you call a black man you call his cell ...

In [9]:
stg1.head()

                                                post          class
0    " : jewish harvard professor noel ignatiev w...  implicit_hate
1   b.higher education is a part of european cult...       not_hate
2   has a problem with  " the whites " " and " " ...       not_hate
3   is yasir qadhi a hate preacher for calling ch...       not_hate
4   rt  " : how three million germans mass murder...       not_hate

# 1) Data Preparation

# 2) Deep Learning Model

# 3) Evaluation of the Model